name: Build AR Image

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "Build #"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          java-package: jdk
          architecture: x64

      - name: Package application
        run: |-
          mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@master
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            export_default_credentials: true

      - name: Build and push
        env:
          AR_HOST: ${{ secrets.AR_HOST }}
          AR_REPO: ${{ secrets.AR_REPO }}
          IMG_NAME: ${{ secrets.IMG_NAME }}
          IMG_TAG: ${{ github.event.inputs.image_tag }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${AR_HOST}${AR_REPO}${IMG_NAME}:${IMG_TAG}
