name: Build AR Image

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "Build #"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          java-package: jdk
          architecture: x64

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Build Image
        env:
          AR_HOST: ${{ secrets.AR_HOST }}
          AR_REPO: ${{ secrets.AR_REPO }}
          IMG_NAME: ${{ secrets.IMG_NAME }}
          IMG_TAG: ${{ github.event.inputs.build_number }}
        run: |-
          mvn clean package -DskipTests

      - name: Publish Image
        env:
          AR_HOST: ${{ secrets.AR_HOST }}
          AR_REPO: ${{ secrets.AR_REPO }}
          IMG_NAME: ${{ secrets.IMG_NAME }}
          IMG_TAG: ${{ github.event.inputs.build_number }}
        run: |-
          mvn deploy -DskipTests
