name: Build and push container image

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "Build #"
        required: true

env:
  AR_HOST: ${{ secrets.AR_HOST }}
  AR_REPO: ${{ secrets.AR_REPO }}
  IMG_NAME: ${{ secrets.IMG_NAME }}
  IMG_TAG: ${{ github.event.inputs.build_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          java-package: jdk
          architecture: x64

      - name: Package Application
        run: |-
          mvn clean package -DskipTests

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: echo ${DOCKER_ACCESS_TOKEN} | docker login --username ${DOCKER_USER} --password-stdin

      - name: Build Docker Image
        run: |-
          docker image build \
            -t ${AR_HOST}${AR_REPO}${IMG_NAME}:${IMG_TAG} \
            .

      - name: Push to GCR
        run: |
          docker login -u oauth2accesstoken -p ${{ secrets.GCP_ACCESS_TOKEN }} https://${AR_HOST}
          dockerpush ${AR_HOST}${AR_REPO}${IMG_NAME}:${IMG_TAG}
