name: Build AR Image

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "Build #"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          java-package: jdk
          architecture: x64

      - name: Package application
        run: |-
          mvn clean package -DskipTests

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${AR_HOST}${AR_REPO}${IMG_NAME}:${IMG_TAG}
        env:
          AR_HOST: ${{ secrets.AR_HOST }}
          AR_REPO: ${{ secrets.AR_REPO }}
          IMG_NAME: ${{ secrets.IMG_NAME }}
          IMG_TAG: ${{ github.event.inputs.image_tag }}